# Generated by Django 2.0.3 on 2018-03-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_auto_20180327_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.FloatField(verbose_name='Valor Unitario')),
                ('valor_total', models.FloatField(verbose_name='Valor Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order')),
            ],
        ),
    ]
