# Generated by Django 2.0.3 on 2018-03-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='buy',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor Total'),
            preserve_default=False,
        ),
    ]
