# Generated by Django 2.0.3 on 2018-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(default=123456789, max_length=20, verbose_name='contact'),
            preserve_default=False,
        ),
    ]
