# Generated by Django 2.0.3 on 2018-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
