# Generated by Django 2.0.3 on 2018-03-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180328_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='data',
        ),
    ]
