# Generated by Django 2.0.3 on 2018-03-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='valor_total',
            field=models.FloatField(default=1, max_length=100, verbose_name='Valor Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='valor_unitario',
            field=models.FloatField(default=1, max_length=100, verbose_name='Valor Unitario'),
            preserve_default=False,
        ),
    ]
