# Generated by Django 2.0.3 on 2018-03-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180327_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='valor_total',
            field=models.FloatField(verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='valor_unitario',
            field=models.FloatField(verbose_name='Valor Unitario'),
        ),
    ]
