# Generated by Django 2.0.3 on 2018-03-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180327_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantidade',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor Total'),
            preserve_default=False,
        ),
    ]
