# Generated by Django 2.0.3 on 2018-03-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180328_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_value',
        ),
    ]
